# dbt_project.yml
name: 'sample_dbt'
version: '1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'market_profile'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Define the target path for compiled SQL files
target-path: "target"
clean-targets:
  - "target"

# Specify the models for each layer
models:
  market_analysis:
    raw:
      materialized: view
      schema: raw
    stg:
      materialized: table
      schema: stg
    # production:
    #   materialized: table