# dbt_project.yml

name: 'sample_dbt'
version: '1.0'
config-version: 2

profile: 'market_profile'

# Define the paths
model-paths: ["models"]

# Define the target path for compiled SQL files
target-path: "target"
clean-targets:
  - "target"

models:
  market_analysis:
    raw:
      +materialized: view
    stg:
      +materialized: table
    # production:
    #   materialized: table