# dbt_project.yml

name: 'sample_dbt'
version: '1.0'
config-version: 2

profile: 'sample_dbt'

# Define the target path for compiled SQL files
target-path: "target"
clean-targets:
  - "target"

models:
  market_analysis:
    raw:
      materialized: view
      schema: public
    # staging:
    #   materialized: view
    # production:
    #   materialized: table